spring:
    datasource:
        url: jdbc:mysql://121.41.27.6:3306/sumec_wechat
        username: wechat
        password: wechat123!
        driverClassName: com.mysql.jdbc.Driver
cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800
